version: '3'
services:
  squid:
    build: .
    image: jonanh/docker-apt-cache
    ports:
      - "3128:3128"
    volumes:
      - ./squid.conf:/etc/squid/squid.conf:z
      - ./data:/var/spool/squid:z
    restart: always

